=== Soyut Fabrika (Abstract Factory)

Birbiriyle ilişkili nesne grupları (nesne ailesi) oluşturmak için soyut fabrika tasarım şablonu
kullanılmaktadır. Soyut fabrika sınıfı bir interface sınıf olarak tanımlanır. İnterface bünyesinde
aynı aileden nesneler oluşturmak için metotlar tanımlanır. Her nesne ailesi bir interface sınıfı
metodu ile temsil edilir.

[plantuml]
....
@startuml

interface AbstractFactory{
   +getStaticObject(): StaticObject
   +getMovingObject(): MovingObject
}

class ConcreteFactory1 implements AbstractFactory{

}

class ConcreteFactory2 implements AbstractFactory{

}

interface StaticObject{
   +getType(): GameObjectType
}

interface MovingObject{
   +getType(): GameObjectType
}

class Wall implements StaticObject{
   +getType(): GameObjectType
}

class Nothing implements StaticObject{
   +getType(): GameObjectType
}

class Monster implements MovingObject{
   +getType(): GameObjectType
}

class GoldMan implements MovingObject{
   +getType(): GameObjectType
}

Test ..> ConcreteFactory1
Test ..> ConcreteFactory2

ConcreteFactory1 .> Wall
ConcreteFactory1 ...> Monster

ConcreteFactory2 ..> Nothing
ConcreteFactory2 ...> GoldMan

@enduml
....

=== Soyut fabrika tasarım şablonu ne zaman kullanılır?

- Kullanıcı sınıf hangi altsınıfların kullanılması gerektiğini bilmiyorsa.
- Kullanıcı sınıf altsınıflardan nasıl nesne üretilmesi gerektiğini bilmiyorsa.
- Kullanıcı sınıf ihtiyaç duyulan nesnelerin oluşturulmasını altsınıflara delege etmek istiyorsa.
- Kullanıcı sınıf birden fazla nesne ailesi ile beraber çalışmak zorunda ise.